variables:


cache:
  key: global
  paths:
    - ci-cache


before_script:
  - time source gitlab-ci-init-python.inc
      # --verbose
      # --verbose
      # --verbose


image: alliance/python


# linting
lint:
  script:
    # we install required packages so linter's isort can know is(n't) a 3rd party package
    - time pip install -r requirements.txt
    - time bin/lint.sh
#  when: manual


# unit tests
test-python:
  services:
    - alliance/mysql
  script:
    - time bin/runtests.sh
#  when: manual