# Attached service containers
services:
  - alliance/mysql

cache:
  key: global
  paths:
    - ci-cache

variables:
  MYSQL_HOST: alliance-mysql
  MYSQL_USER: ephemeral_user
  MYSQL_PASSWORD: password
  MYSQL_DATABASE: ephemeral_db
  MYSQL_ROOT_PASSWORD: password

  PYTHON_VERSION: py35

before_script:
  - source gitlab-ci-init-python.inc

image: alliance/python

# linting
lint:
  script:
    # we install required packages so linter's isort can know is(n't) a 3rd party package
    - pip install -r requirements.txt
    - bin/lint.sh

# basic test
test-python:
  script:
    - bin/runtests.sh
